repos:
    - repo: local
      hooks:
          - id: forge-fmt
            name: Forge format check
            entry: bash -c 'cd loan-provider && forge fmt --check'
            language: system
            types: [solidity]
            pass_filenames: false
            always_run: true

          - id: forge-build
            name: Forge build
            entry: bash -c 'cd loan-provider && forge build'
            language: system
            pass_filenames: false
            always_run: true

          - id: forge-test
            name: Forge test
            entry: bash -c 'cd loan-provider && make test'
            language: system
            pass_filenames: false
            always_run: true

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
            args: ["--maxkb=1000"]
          - id: check-merge-conflict
